# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_ekran_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 671)
        MainWindow.setMaximumSize(QtCore.QSize(1164, 671))
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
"    background:#f2f2f2;\n"
"}\n"
"\n"
"QStatusBar \n"
"{\n"
"    border-top:1px solid #aaaaaa;\n"
"    min-height:20px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.2 #f4f4f4, stop:1 #e4e4e4);\n"
"}\n"
"\n"
"QFrame#window\n"
"{\n"
"    padding:0px;\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-style:solid;/*边框类型*/\n"
"    /*用渐变色可以营造光晕边框效果*/\n"
"    border-color:qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #999999, stop:1 #ffffff)/*上边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #999999, stop:1 #ffffff)/*右边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #999999, stop:1 #ffffff)/*下边框渐变色*/\n"
"      qlineargradient(x1:1, y1:0, x2:0, y2:0, stop:0 #999999, stop:1 #ffffff);/*左边框渐变色*/\n"
"}\n"
"\n"
"\n"
"QWidget#titlebar\n"
"{\n"
"    min-height:25px;/*用min-height设置标题栏高度*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.2 #e4e4e4, stop:1 #d4d4d4);/*渐变背景色*/\n"
"    border-bottom:1px solid #aaaaaa;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.kullaniciResmi = QtWidgets.QLabel(self.centralwidget)
        self.kullaniciResmi.setMinimumSize(QtCore.QSize(230, 240))
        self.kullaniciResmi.setMaximumSize(QtCore.QSize(230, 240))
        self.kullaniciResmi.setText("")
        self.kullaniciResmi.setPixmap(QtGui.QPixmap(":/iconlar/ticket.png"))
        self.kullaniciResmi.setScaledContents(True)
        self.kullaniciResmi.setObjectName("kullaniciResmi")
        self.horizontalLayout.addWidget(self.kullaniciResmi)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.adText = QtWidgets.QLineEdit(self.centralwidget)
        self.adText.setClearButtonEnabled(True)
        self.adText.setObjectName("adText")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.adText)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.soyadText = QtWidgets.QLineEdit(self.centralwidget)
        self.soyadText.setClearButtonEnabled(True)
        self.soyadText.setObjectName("soyadText")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.soyadText)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fakulteCombo = QtWidgets.QComboBox(self.centralwidget)
        self.fakulteCombo.setIconSize(QtCore.QSize(20, 20))
        self.fakulteCombo.setFrame(True)
        self.fakulteCombo.setObjectName("fakulteCombo")
        self.fakulteCombo.addItem("")
        self.fakulteCombo.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fakulteCombo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.kaydetButton = QtWidgets.QPushButton(self.centralwidget)
        self.kaydetButton.setMinimumSize(QtCore.QSize(0, 0))
        self.kaydetButton.setMaximumSize(QtCore.QSize(200, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconlar/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kaydetButton.setIcon(icon)
        self.kaydetButton.setObjectName("kaydetButton")
        self.horizontalLayout_2.addWidget(self.kaydetButton)
        self.silButton = QtWidgets.QPushButton(self.centralwidget)
        self.silButton.setMinimumSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconlar/icons/sil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.silButton.setIcon(icon1)
        self.silButton.setObjectName("silButton")
        self.horizontalLayout_2.addWidget(self.silButton)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 26))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionA = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconlar/icons/ac.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionA.setIcon(icon2)
        self.actionA.setObjectName("actionA")
        self.actionDB_Ba_lant_s_Kontrol_Et = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconlar/icons/yenile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDB_Ba_lant_s_Kontrol_Et.setIcon(icon3)
        self.actionDB_Ba_lant_s_Kontrol_Et.setObjectName("actionDB_Ba_lant_s_Kontrol_Et")
        self.actionKaydet = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconlar/icons/kaydet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKaydet.setIcon(icon4)
        self.actionKaydet.setObjectName("actionKaydet")
        self.action_k = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconlar/icons/cikis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_k.setIcon(icon5)
        self.action_k.setObjectName("action_k")
        self.actionDB_Kontrol = QtWidgets.QAction(MainWindow)
        self.actionDB_Kontrol.setIcon(icon3)
        self.actionDB_Kontrol.setObjectName("actionDB_Kontrol")
        self.actionKullan_c_Ekle = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconlar/icons/ekle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKullan_c_Ekle.setIcon(icon6)
        self.actionKullan_c_Ekle.setObjectName("actionKullan_c_Ekle")
        self.actionHakk_nda = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconlar/icons/sifremi_unuttum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHakk_nda.setIcon(icon7)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.menuDosya.addAction(self.actionA)
        self.menuDosya.addAction(self.actionDB_Ba_lant_s_Kontrol_Et)
        self.menuDosya.addAction(self.actionKaydet)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.action_k)
        self.menuYard_m.addAction(self.actionHakk_nda)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuYard_m.menuAction())
        self.toolBar.addAction(self.actionDB_Kontrol)
        self.toolBar.addAction(self.actionKullan_c_Ekle)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ad Soyad"))
        self.label_2.setText(_translate("MainWindow", "Sorun Bilgisi"))
        self.label_8.setText(_translate("MainWindow", "Sorun Açıklaması"))
        self.label_4.setText(_translate("MainWindow", "Sorun Kategorisi"))
        self.fakulteCombo.setCurrentText(_translate("MainWindow", "Donanım"))
        self.fakulteCombo.setItemText(0, _translate("MainWindow", "Donanım"))
        self.fakulteCombo.setItemText(1, _translate("MainWindow", "Yazılım"))
        self.kaydetButton.setText(_translate("MainWindow", "Sorun Bildir"))
        self.silButton.setText(_translate("MainWindow", "Kapat"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionA.setText(_translate("MainWindow", "Aç"))
        self.actionDB_Ba_lant_s_Kontrol_Et.setText(_translate("MainWindow", "DB Bağlantısı Kontrol Et"))
        self.actionKaydet.setText(_translate("MainWindow", "Kaydet"))
        self.action_k.setText(_translate("MainWindow", "Çıkış"))
        self.actionDB_Kontrol.setText(_translate("MainWindow", "DB Kontrol"))
        self.actionKullan_c_Ekle.setText(_translate("MainWindow", "Kullanıcı Ekle"))
        self.actionHakk_nda.setText(_translate("MainWindow", "Hakkında"))
import kullanici_giris_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
